version: "3.7"

services:
  database:
    image: postgres
    container_name: database_postgre
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=database
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: rentx
    ports:
      - 3000:3000
    volumes:
      - .:/user/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local